name: "Genarate tags from GitHub"
description: "Generate tags from GitHub"
author: "Pianoopera"
inputs:
  github_branch:
    description: "GitHub branch prefix is feature"
    required: false
    default: "main"

outputs:
  tags:
    description: "Tags"
    value: ${{ steps.tags.outputs.tags }}

runs:
  using: composite
  steps:
    - name: OutPut tags
      if: ${{ inputs.github_branch != 'main' }}
      shell: bash
      id: tags
      run: |
        echo "tags=$(echo ${{ inputs.github_branch }} | sed -e 's/feature\///g')" >> $GITHUB_OUTPUT
