name: "Genarate tags from GitHub"
description: "Generate tags from GitHub"
author: "Pianoopera"
inputs:
  github_branch:
    description: "GitHub branch prefix is feature"
    required: false
  github_tag:
    description: "GitHub tag command list"
    required: false

outputs:
  tags:
    description: "Tags"
    value: |
      ${{ steps.branch.outputs.tags }}
      ${{ steps.tag.outputs.tags }}

runs:
  using: composite
  steps:
    - name: OutPut from github branch
      if: ${{ inputs.github_branch != '' && inputs.github_tag == '' }}
      shell: bash
      id: branch
      run: |
        echo "tags=$(echo ${{ inputs.github_branch }} | sed -e 's/feature\///g')" >> $GITHUB_OUTPUT

    - name: OutPut from github tag list
      if: ${{ inputs.github_tag != '' && inputs.github_branch == '' }}
      shell: bash
      id: tag
      run: |
        fmt_tags=$(echo "${{ inputs.github_tag }}" | sed ':a;N;$!ba;s/\n/|/g')
        echo "tags=$(echo $fmt_tags)" >> $GITHUB_OUTPUT

    - name: failure inputs
      shell: bash
      if: ${{ inputs.github_branch == '' && inputs.github_tag == '' }}
      run: |
        echo "Please provide either github_branch or github_tag"
        exit 1

    - name: failure outputs
      shell: bash
      if: ${{ steps.branch.outputs.tags == '' && steps.tag.outputs.tags == '' }}
      run: |
        echo "Please provide either github_branch or github_tag"
        exit 1
