name: Run Custom Action

on:
  pull_request:
    branches: [main]

jobs:
  run-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: git taglist
        id: taglist
        run: |
          echo 'MULTILINE_INPUT<<EOF' >> $GITHUB_ENV
          echo '' >> $GITHUB_ENV
          echo 'list1' >> $GITHUB_ENV
          echo 'list2' >> $GITHUB_ENV
          echo 'list3' >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Run custom action
        id: run-action
        uses: ./
        with:
          github_tag: ${{ env.MULTILINE_INPUT }}

      - name: Test list
        if: ${{ steps.run-action.outputs.tags != 'list1|list2|list3' }}
        run: |
          echo "tags: ${{ steps.run-action.outputs.tags }}"
          exit 1
